service logger
    command = /sbin/loggerd
    restart = always

service network
    command = /sbin/netd
    restart = on-failure

service ttyd
    command = /sbin/ttyd
    restart = always

service login
    command = /sbin/logind
    restart = always
